#Estagio 1 --base
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
RUN mkdir /app
WORKDIR /app
EXPOSE 80/tcp

#Estagio 2 --pblish
FROM microsoft/dotnet:2.2-sdk AS publish
WORKDIR /app
COPY mvc1.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o dist

#Estagio 3 --final
FROM base As final
WORKDIR /dist
COPY --from=publish /app/dist .
ENTRYPOINT ["dotnet", "mvc1.dll"]